language: python
python:
  - "2.7"

notifications:
  email: false

# Install scipy without need to compile, taken from Theano
# Setup anaconda
before_install:
# Install miniconda to avoid compiling scipy
  - mkdir -p download
  - cd download
  - wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - cd ..
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy=0.16 nose theano
  - pip install coveralls
  - python setup.py install

script:
  - nosetests --verbosity=2 --with-coverage --cover-package=pymanopt
  - cd examples && sh run_all.sh && cd ..

after_success:
  - coveralls
